[package]
name = "kovi-plugin-siliconflow"
version = "0.5.0"
edition = "2024"

[dependencies]
kovi.workspace = true
kovi-plugin-expand-napcat = "0.3.1"
reqwest = { version = "0.12.12", features = ["json"] }
serde = "1.0.218"
thiserror = "2.0.12"
